apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nessus-pv-claim
  namespace: nessus
spec:
  storageClassName: ebs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
