apiVersion: v1
kind: Service
metadata:
  name: nessus
  namespace: nessus
spec:
  selector:
    app: nessus
  type: LoadBalancer
  loadBalancerSourceRanges:
    - 98.146.223.15/32
    - 159.142.0.0/16
  ports:
    - protocol: TCP
      port: 8834
      targetPort: 8834

