apiVersion: v1
kind: Service
metadata:
  name: flux-memcached
spec:
  ports:
    - port: 11211
      targetPort: memcached
      protocol: TCP
      name: memcached
  selector:
    app: flux-memcached
