apiVersion: constraints.gatekeeper.sh/v1alpha1
kind: ContainerResources
metadata:
  name: containerresources
spec:
  match:
    namespaces:
      - idp-dev
    kinds:
      - apiGroups: ["apps"]
        kinds: ["Deployment"]
