service:
  annotations: {}
  type: ClusterIP
  ports:
    - name: beats
      port: 5044
      protocol: TCP
      targetPort: 5044
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080

logstashConfig:
  logstash.yml: |
     http.host: "0.0.0.0"
     filter {
       if [message] =~ "^\{" {
         json {
           source => "message"
         }
       }
     }

