# This is the role for nessus deploys
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: nessus
  name: deploy
rules:
- apiGroups: [""]
  resources: ["deployments", "services", "persistentvolumeclaims"]
  verbs: ["get", "create", "update"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["patch", "get", "create", "update"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["list", "create", "update"]
- apiGroups: ["extensions"]
  resources: ["deployments"]
  verbs: ["get", "patch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: deploy
  namespace: default
subjects:
- kind: User
  name: deploy
  apiGroup: "rbac.authorization.k8s.io"
roleRef:
  kind: Role
  name: deploy
  apiGroup: "rbac.authorization.k8s.io"

