apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux
  namespace: flux
spec:
  template:
    spec:
      containers:
        - name: flux
          args:
            - --manifest-generation=true
            - --memcached-hostname=memcached.flux
            - --memcached-service=
            - --ssh-keygen-dir=/var/fluxd/keygen
            - --git-branch=master
            - --git-path=clusterconfig/tspencertest
            - --git-user=tspencertest
            - --git-email=tspencertest@users.noreply.github.com
            - --git-url=git@github.com:18F/identity-secops

