apiVersion: spinnaker.armory.io/v1alpha2
kind: SpinnakerService
metadata:
  name: spinnaker
  namespace: identity-system
spec:
  spinnakerConfig:
    config:
      version: 2.15.1
      persistentStorage:
        persistentStoreType: s3
        s3:
          bucket: "spinnaker-config-cockatoo"
          accessKeyId: "spinnaker-s3-bot"
          secretAccessKey: "32HV69ld5Yi71QotSrFoPJhLwRkc8kqwLdZXsESf"
          rootFolder: front50
    profiles:
      clouddriver: {}
      deck:
        settings-local.js: |
          window.spinnakerSettings.feature.kustomizeEnabled = true;
          window.spinnakerSettings.feature.artifactsRewrite = true;
      echo: {}   
      fiat: {}   
      front50: {}
      gate: {}   
      igor: {}   
      kayenta: {}
      orca: {}   
      rosco: {}  
    service-settings:
      clouddriver: {}
      deck: {}
      echo: {}
      fiat: {}
      front50: {}
      gate: {}
      igor: {}
      kayenta: {}
      orca: {}
      rosco: {}
    files: {}
  expose:
    type: service
    service:
      type: LoadBalancer
      annotations: {}
      overrides:
        deck:
          annotations:
            service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-west-2:894947205914:certificate/8aef1337-49e4-42a7-afeb-1b9b15f9c953"
            service.beta.kubernetes.io/aws-load-balancer-backend-protocol: https
        gate:
          annotations:
            service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-west-2:894947205914:certificate/4e7284a0-1746-4a81-8f69-863576d045dc"
            service.beta.kubernetes.io/aws-load-balancer-backend-protocol: https
        gate-x509:
          annotations:
            service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
            service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-west-2:894947205914:certificate/4e7284a0-1746-4a81-8f69-863576d045dc"
          publicPort: 443

