service:
  annotations: {}
  type: ClusterIP
  ports:
    - name: beats
      port: 5044
      protocol: TCP
      targetPort: 5044
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
logstashConfig:
  logstash.yml: |
    output.elasticsearch:
      hosts: ["http://elasticsearch-master:9200"]

